config/routes.rb
Rails.application.routes.draw do

  
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'pages', to: 'welcome#pages'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
        
    end
    
    def about
        
    end
    
    def pages
        
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<body style="background-color:DarkTurquoise;">

<h1 style="text-align:center;">About</h1>

<%= link_to 'Home', root_path %>
<br>
<%= link_to 'Pages', pages_path %>

app/views/welcome/home.html.erb
<body style="background-color:plum;">

<h1 style="text-align:center;">Stock Tracker</h1>

<%= link_to 'About', about_path %>
<br>
<%= link_to 'Pages', pages_path %>

app/views/welcome/pages.html.erb
<body style="background-color:Lavender;">

<h1 style="text-align:center;">Pages</h1>

<%= link_to 'Home', root_path %>
<br>
<%= link_to 'About', about_path %>